### ISSUE TITLE
fails to build in ubuntu 12.10 due to stpcpy redefine

### ISSUE THREAD

**Issue by brazilofmux** [brazilofmux/tinymux#682]
Original [issue 680](https://code.google.com/p/tinymux/issues/detail?id=680) created by brazilofmux on 2012-10-10T18:21:15.000Z:

tinymux 2.6.5.33 fails to build in ubuntu 12.10 due to the stpcpy redefine:
g++  -g -O   -DWOD_REALMS -DREALITY_LVLS     -c slave.cpp
slave.cpp: In function ‘int query(char_, char_)’:
slave.cpp:51:7: error: inlining failed in call to always_inline ‘char\* stpcpy(char_, const char_) throw ()’: function not inlinable

see the full log of 2.6.5.28:
https://launchpadlibrarian.net/118104126/buildlog_ubuntu-quantal-i386.tinymux_2.6.5.28-1build1_FAILEDTOBUILD.txt.gz

the function should be renamed to not clash with the posix 2008 function in string.h, or better just use the posix 2008 version.
